- name: IN_PRODUCTION
  value: 'True'
- name: COMPONENT
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['component']
- name: MYSQL_HOST
  valueFrom:
    secretKeyRef:
      name: pyspaceship-mysql
      key: host
- name: MYSQL_PORT
  valueFrom:
    secretKeyRef:
      name: pyspaceship-mysql
      key: port
- name: MYSQL_USERNAME
  valueFrom:
    secretKeyRef:
      name: pyspaceship-mysql
      key: username
- name: MYSQL_PASSWORD
  valueFrom:
    secretKeyRef:
      name: pyspaceship-mysql
      key: password
- name: MYSQL_DB
  valueFrom:
    secretKeyRef:
      name: pyspaceship-mysql
      key: db
- name: REDIS_HOST
  valueFrom:
    secretKeyRef:
      name: pyspaceship-redis
      key: host
- name: REDIS_PORT
  valueFrom:
    secretKeyRef:
      name: pyspaceship-redis
      key: port
- name: REDIS_DB
  valueFrom:
    secretKeyRef:
      name: pyspaceship-redis
      key: db
- name: SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: pyspaceship-session
      key: secret_key
- name: SENDGRID_KEY
  valueFrom:
    secretKeyRef:
      name: pyspaceship-sendgrid
      key: secret_key
- name: GOOGLE_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: pyspaceship-google-oauth
      key: client_id
- name: GOOGLE_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: pyspaceship-google-oauth
      key: secret
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: /srv/pyspaceship/google-app-creds/key.json
- name: SERVER_NAME
  value: '${namespace}.spaceshipearth.org'
