apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspaceship-deployment
spec:
  selector:
    matchLabels:
      app: pyspaceship
  replicas: {$eval: replicas}
  template:
    metadata:
      labels:
        app: pyspaceship
    spec:
      containers:
      - name: pyspaceship
        image: {$eval: image}
        imagePullPolicy: "Always"
        livenessProbe:
          httpGet:
            path: /health
            port: 9876
        env:
          - name: IN_PRODUCTION
            value: 'True'
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: pyspaceship-mysql
                key: host
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: pyspaceship-mysql
                key: port
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: pyspaceship-mysql
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pyspaceship-mysql
                key: password
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: pyspaceship-mysql
                key: db
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: pyspaceship-session
                key: secret_key
          - name: SENDGRID_KEY
            valueFrom:
              secretKeyRef:
                name: pyspaceship-sendgrid
                key: secret_key
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: pyspaceship-google-oauth
                key: client_id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: pyspaceship-google-oauth
                key: secret
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /srv/pyspaceship/google-app-creds/key.json
        volumeMounts:
          - name: google-app-creds
            mountPath: /srv/pyspaceship/google-app-creds
      volumes:
        - name: google-app-creds
          secret:
            secretName: google-app-creds
