apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pyspaceship-ingress
  namespace: {$eval: namespace}
spec:
  tls:
    - hosts:
      - spaceshipearth.org
      - www.spaceshipearth.org
      - "${namespace}.spaceshipearth.org"
    - secretName: spaceshipearth-org-tls
  rules:
  - host: spaceshipearth.org
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
  - host: www.spaceshipearth.org
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
  - host: "${namespace}.spaceshipearth.org"
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
