apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pyspaceship-ingress
spec:
  tls:
    - hosts:
      - spaceshipearth.org
      - www.spaceshipearth.org
      - test.spaceshipearth.org
    - secretName: wildcard-spaceshipearth-org-tls

  rules:
  - host: spaceshipearth.org
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
  - host: test.spaceshipearth.org
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
  - host: www.spaceshipearth.org
    http:
      paths:
      - backend:
          serviceName: pyspaceship-service
          servicePort: spaceship-port
